create table BOOKS
  (BOOK_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL,
  abbreviation VARCHAR(10) NOT NULL);

create table VERSES (
  BOOK_ID INTEGER NOT NULL REFERENCES BOOKS(BOOK_ID) on delete cascade,
  CHAPTER smallint NOT NULL,
  VERSE smallint NOT NULL,
  PRIMARY KEY (BOOK_ID, CHAPTER, VERSE)
);

CREATE TABLE VERSE_TRANSLATIONS
  (VERSE_TRANSLATION_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  LANGUAGE VARCHAR(5) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  CONTENT TEXT NOT NULL,
  BOOK_ID   INT NOT NULL,
  CHAPTER   INT NOT NULL,
  VERSE     INT NOT NULL,
  CONSTRAINT FK_VERSE_TRANSLATIONS_VERSES
    FOREIGN KEY (BOOK_ID, CHAPTER, VERSE) REFERENCES VERSES(BOOK_ID, CHAPTER, VERSE) ON DELETE CASCADE
);

create table VERSE_POST (
  VERSE_POST_ID UUID PRIMARY KEY DEFAULT gen_random_uuid()
);

CREATE TABLE verse_noticed (
  BOOK_ID   INT NOT NULL,
  CHAPTER   INT NOT NULL,
  VERSE     INT NOT NULL,
  verse_post_id UUID,
  PRIMARY KEY (BOOK_ID, CHAPTER, VERSE),
  CONSTRAINT fk_verse_noticed_verse
    FOREIGN KEY (BOOK_ID, CHAPTER, VERSE) REFERENCES VERSES(BOOK_ID, CHAPTER, VERSE) ON DELETE CASCADE,
  CONSTRAINT fk_verse_noticed_post
    FOREIGN KEY (verse_post_id) REFERENCES verse_post(verse_post_id) ON DELETE SET NULL
);