DROP TABLE IF EXISTS VERSE_POST CASCADE;
DROP TABLE IF EXISTS VERSE_NOTICED CASCADE;
DROP TABLE IF EXISTS VERSE_TRANSLATIONS CASCADE;
DROP TABLE IF EXISTS VERSES CASCADE;
DROP TABLE IF EXISTS BOOKS CASCADE;

