-- Populate with 66 books (Protestant canon order)
INSERT INTO books (name, abbreviation, BOOK_ID) VALUES
('Genesis', 'Gen', 1),
('Exodus', 'Exo', 2),
('Leviticus', 'Lev', 3),
('Numbers', 'Num', 4),
('Deuteronomy', 'Deu', 5),
('Joshua', 'Jos', 6),
('Judges', 'Jdg', 7),
('Ruth', 'Rth', 8),
('1 Samuel', '1Sa', 9),
('2 Samuel', '2Sa', 10),
('1 Kings', '1Ki', 11),
('2 Kings', '2Ki', 12),
('1 Chronicles', '1Ch', 13),
('2 Chronicles', '2Ch', 14),
('Ezra', 'Ezr', 15),
('Nehemiah', 'Neh', 16),
('Esther', 'Est', 17),
('Job', 'Job', 18),
('Psalms', 'Psa', 19),
('Proverbs', 'Pro', 20),
('Ecclesiastes', 'Ecc', 21),
('Song of Solomon', 'Sng', 22),
('Isaiah', 'Isa', 23),
('Jeremiah', 'Jer', 24),
('Lamentations', 'Lam', 25),
('Ezekiel', 'Eze', 26),
('Daniel', 'Dan', 27),
('Hosea', 'Hos', 28),
('Joel', 'Joe', 29),
('Amos', 'Amo', 30),
('Obadiah', 'Oba', 31),
('Jonah', 'Jon', 32),
('Micah', 'Mic', 33),
('Nahum', 'Nah', 34),
('Habakkuk', 'Hab', 35),
('Zephaniah', 'Zep', 36),
('Haggai', 'Hag', 37),
('Zechariah', 'Zec', 38),
('Malachi', 'Mal', 39),
('Matthew', 'Mat', 40),
('Mark', 'Mar', 41),
('Luke', 'Luk', 42),
('John', 'Joh', 43),
('Acts', 'Act', 44),
('Romans', 'Rom', 45),
('1 Corinthians', '1Co', 46),
('2 Corinthians', '2Co', 47),
('Galatians', 'Gal', 48),
('Ephesians', 'Eph', 49),
('Philippians', 'Php', 50),
('Colossians', 'Col', 51),
('1 Thessalonians', '1Th', 52),
('2 Thessalonians', '2Th', 53),
('1 Timothy', '1Ti', 54),
('2 Timothy', '2Ti', 55),
('Titus', 'Tit', 56),
('Philemon', 'Phm', 57),
('Hebrews', 'Heb', 58),
('James', 'Jam', 59),
('1 Peter', '1Pe', 60),
('2 Peter', '2Pe', 61),
('1 John', '1Jo', 62),
('2 John', '2Jo', 63),
('3 John', '3Jo', 64),
('Jude', 'Jud', 65),
('Revelation', 'Rev', 66);
